FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Florida Man Generator

This API allows users to find Florida Man news articles. The API serves JSON data extended by the Mason hypermedia format. Users can find articles and also add new articles. They can also list articles added by other users to see what they have come up with.

# Group Link Relations

This section described custom link relations defined in this API. These are not resources. The API also uses 
[IANA link relations](http://www.iana.org/assignments/link-relations/link-relations.xhtml) where applicable. Custom link relations are CURIEs that use the floman prefix. 

## add-article

This is a control that is used to add an article to the associated collection resource. The control includes a JSON schema and must be accessed with POST. 

## articles-all

Leads to the root level articles collection which is a list of all articles known to the API.

## article-by-date

Leads to an article item resource associated with the date provided.

## add-user

This is a control that is used to add a user to the associated collection resource. The control includes a JSON schema and must be accessed with POST. 

## users-all

Leads to the root level users collection which is a list of all users known to the API.

## owned-article

Leads to an added article item resource associated with the user provided.

## user-by-name

Leads to an user item resource associated with the username provided.

## add-addedarticle

This is a control that is used to add an added article to the associated collection resource. The control includes a JSON schema and must be accessed with POST. 

## addedarticles-all

Leads to the root level users collection which is a list of all added articles known to the API.

## addedarticle-by-owner

Leads to an added article item resource associated with the owner provided.

# Group Profiles

This section includes resource profiles which provide semantic descriptions for the attributes of each resource, as well as the list of controls (by link relation) available from that resource.

## Article Profile

Profile definition for all article related resources.

### Link Relations

This section lists all possible link relations associated with articles; not all of them are necessarily present on each resource type. The following link relations from the floman namespace are used:

 * [add-article](reference/link-relations/add-article)
 * [articles-all](reference/link-relations/articles-add)
 * [article-by-date](reference/link-relations/article-by-date)
 
The following [IANA RFC5988](http://www.iana.org/assignments/link-relations/link-relations.xhtml) link relations are also used:

 * collection
 * items
 * self
 * edit
 * delete

### Semantic Descriptors

#### Data Type Article

 * `date`: Date of the article. Mandatory and unique.
 * `link`: Link to the article. Optional.
 * `headline`: Headline of the article. Mandatory

## User Profile

Profile definition for all user related resources.

### Link Relations

This section lists all possible link relations associated with tracks; not all of them are necessarily present on each resource type. The following link relations from the floman namespace are used:

 * [add-user](reference/link-relations/add-user)
 * [users-all](reference/link-relations/users-all)
 * [user-by-name](reference/link-relations/user-by-name)
 * [owned-article](reference/link-relations/owned-article)
 
The following [IANA RFC5988](http://www.iana.org/assignments/link-relations/link-relations.xhtml) link relations are also used:

 * collection
 * items
 * self
 * edit
 * delete

### Semantic Descriptors

#### Data Type Track

 * `username`: Name of the user. Mandatory and unique.

## Added article Profile

Profile definition for all added article related resources.

### Link Relations

This section lists all possible link relations associated with tracks; not all of them are necessarily present on each resource type. The following link relations from the floman namespace are used:

 * [add-addedarticle](reference/link-relations/add-addedarticle)
 * [addedarticles-all](reference/link-relations/addedarticles-all)
 * [addedarticle-by-owner](reference/link-relations/addedarticle-by-owner)
 
The following [IANA RFC5988](http://www.iana.org/assignments/link-relations/link-relations.xhtml) link relations are also used:

 * collection
 * items
 * self
 * edit
 * delete
 * owner

### Semantic Descriptors

#### Data Type Track

 * `date`: Date of the article. Optional.
 * `link`: Link to the article. Optional.
 * `headline`: headline of the article. Mandatory.
 * `owner_id`: ID of the owner of the article. Mandatory. Points to some user.

## Error Profile

Profile definition for all errors returned by the API. See [Mason error control](https://github.com/JornWildt/Mason/blob/master/Documentation/Mason-draft-2.md#property-name-error) for more information about errors.

+ Attributes

    + resource_url (string, required) - URI of the resource the error was generated from. 

# Group Entry

This group contains the entry point of the API

## Entry Point [/api/]

### Get entry point [GET]

Get the API entry point

+ Request

    + Headers
    
            Accept: application/vnd.mason+json
            
+ Response 200 (application/vnd.mason+json)

    + Body
    
            {
                "@namespaces": {
                    "floman": {
                        "name": "/floridaman/link-relations#"
                    }
                },
                "@controls": {
                    "floman:articles-all": {
                        "href": "/api/articles/"
                    },
                    "floman:users-all": {
                        "href": "/api/users/"
                    },
                    "floman:addedarticles-all": {
                        "href": "/api/addedarticles/"
                    }
                }
            }

 
# Group Articles

All of these resources use the [Article Profile](reference/profiles/article-profile). In error scenarios [Error Profile](reference/profiles/error-profile) is used.

## Article Collection [/api/articles/]

A list of all articles known to the API. You can also add new articles with POST, edit articles using PUT and delete articles using DELETE.

### List all articles [GET]

Get a list of all articles known to the API.

+ Relation: articles-all
+ Request

    + Headers
    
            Accept: application/vnd.mason+json

+ Response 200 (application/vnd.mason+json)
    
    + Body

            {
                "@namespaces": {
                    "floman": {
                        "name": "/floridaman/link-relations#"
                    }
                },
                "@controls": {
                    "floman:add-article": {
                        "href": "/api/articles/",
                        "title": "Add a new article",
                        "encoding": "json",
                        "method": "POST",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "date": {
                                    "description": "Date of the article",
                                    "type": "string",
                                    "pattern": "^[0-3][0-9]\.[0-1][0-9]\.[0-9][0-9][0-9][0-9]$"
                                },
                                "link": {
                                    "description": "Link to the article",
                                    "type": "string"
                                },
                                "headline": {
                                    "description": "Headline of the article",
                                    "type": "string"
                                }
                            },
                            "required": ["date"]
                        }
                    },
                    "floman:edit-article": {
                        "href": "/api/articles/02.01.2019"
                        "title": "Edit this article",
                        "encoding": "json",
                        "method": "PUT",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "date": {
                                    "description": "Date of the article, that will be edited",
                                    "type": "string",
                                    "pattern": "^[0-3][0-9]\.[0-1][0-9]\.[0-9][0-9][0-9][0-9]$"
                                },
                                "link": {
                                    "description": "Link to the article",
                                    "type": "string"
                                },
                                "headline": {
                                    "description": "Headline of the article",
                                    "type": "string"
                                }
                            },
                            "required": []
                        }
                    },
                    "floman:article-by-date": {
                        "href": "/api/articles/?{date}",
                        "title": "Article by date",
                        "isHrefTemplate": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "date": {
                                    "description": "Date of the article you want to find",
                                    "type": "string",
                                    "pattern": "^[0-3][0-9]\.[0-1][0-9]\.[0-9][0-9][0-9][0-9]$"
                                }
                            },
                            "required": ["date"]
                        }
                    }
                },
                "items": [
                    {
                        "date": "02.01.2019"
                        "link": "https://www.wcjb.com/content/news/Florida-man-doesnt-get-straw-attacks-McDonalds-employee-503812581.html",
                        "headline": "Florida man doesn't get straw, attacks McDonald's employee",
                        "modtime": "Some modificationg date"
                    }
                ]
            }
            
### Add article [POST]

Adds a new article. The article representation must be valid against the article schema.

+ Relation: add-article
+ Request (application/json)

    + Headers

            Accept: application/vnd.mason+json
        
    + Body
    
            {
                "date": "05.05.2015",
                "link": "http://google.com",
                "headline": "Some Headline"
            }

+ Response 201

    + Headers
    
            Location: /api/articles/05.05.2015/

+ Response 400 (application/vnd.mason+json)

    The client is trying to send a JSON document that doesn't validate against the schema, or has non-existent release date.

    + Body
    
            {
                "resource_url": "/api/articles/05.05.2015/",
                "@error": {
                    "@message": "Invalid JSON document",
                    "@messages": ["'date' and 'headline' are required properties"]
                },
                "@controls": {
                    "profile": {
                        "href": "/profiles/error/"
                    }
                }
            }

+ Response 409 (application/vnd.mason+json)

    The client is trying to add an article with a date that's already used by another article.

    + Body
    
            {
                "resource_url": "/api/articles/05.05.2015",
                "@error": {
                    "@message": "Already exists",
                    "@messages": [
                        "An article with date '05.05.2015' already exists."
                    ]
                },
                "@controls": {
                    "profile": {
                        "href": "/profiles/error/"
                    }
                }
            }
            

+ Response 415 (application/vnd.mason+json)

    The client did not use the proper content type, or the request body was not valid JSON.

    + Body
        
            {
                "resource_url": "/api/articles/05.05.2015",
                "@error": {
                    "@message": "Unsupported media type",
                    "@messages": [
                        "Use JSON"
                    ]
                },
                "@controls": {
                    "profile": {
                        "href": "/profiles/error-profile/"
                    }
                }
            }

### Edit article [PUT]

Replace the article's representation with a new one. Missing optinal fields will be set to null. Must validate against the article schema. 

+ Relation: edit-article
+ Request (application/json)

    + Headers
        
            Accept: application/vnd.mason+json
        
    + Body
    
            {
                "date": "05.05.2015",
                "link": "http://google.com",
                "headline": "Some Headline"
            }
        
+ Response 204


+ Response 400 (application/vnd.mason+json)

    The client is trying to send a JSON document that doesn't validate against the schema.

    + Body
    
            {
                "resource_url": "/api/articles/05.05.2015/",
                "@error": {
                    "@message": "Invalid JSON document",
                    "@messages": ["'date' and 'headline' are required properties"]
                },
                "@controls": {
                    "profile": {
                        "href": "/profiles/error/"
                    }
                }
            }

+ Response 404 (application/vnd.mason+json)

    The client is trying to edit an article that doesn't exist. 

    + Body
    
            {
                "resource_url": "/api/articles/05.05.2015",
                "@error": {
                    "@message": "Article not found",
                    "@messages": [null]
                },
                "@controls": {
                    "profile": {
                        "href": "/profiles/error/"
                    }
                }
            }
            
+ Response 409 (application/vnd.mason+json)

    The client is trying to change the date of the article to a one that is already in use.

    + Body
    
            {
                "resource_url": "/api/articles/05.05.2015",
                "@error": {
                    "@message": "Provided date is already in use.",
                    "@messages": ["Date '05.05.2015' is already used by other article"]
                },
                "@controls": {
                    "profile": {
                        "href": "/profiles/error/"
                    }
                }
            }
        
+ Response 415 (application/vnd.mason+json)

    The client sent a request with the wrong content type or the request body was not valid JSON.

    + Body
        
            {
                "resource_url": "/api/articles/05.05.2015",
                "@error": {
                    "@message": "Unsupported media type",
                    "@messages": [
                        "Use JSON"
                    ]
                },
                "@controls": {
                    "profile": {
                        "href": "/profiles/error-profile/"
                    }
                }
            }

### Delete article [DELETE]

Deletes the article.

+ Relation: delete-article
+ Request

    + Headers
        
            Accept: application/vnd.mason+json
        
+ Response 204

+ Response 404 (application/vnd.mason+json)

    The client is trying to delete an article that doesn't exist. 

    + Body
    
            {
                "resource_url": "/api/articles/05.05.2015",
                "@error": {
                    "@message": "Article not found",
                    "@messages": [null]
                },
                "@controls": {
                    "profile": {
                        "href": "/profiles/error/"
                    }
                }
            }

## Article item [/api/articles/?{date}]

A single article known to the API. The article is fetched using the date of the article. You can only get the article from associated collection using GET.

+ Parameters

    + date (string, required) - Date of the article to be fetched.
    
        + Members
        
            + `date`
            + `link`
            + `headline`
            + `modtime`

### Get Article [GET]

Gets the article from collection.

+ Relation: article-by-date
+ Request

    + Headers
    
            Accept: application/vnd.mason+json

+ Response 200 (application/vnd.mason+json)
    
    + Body

            {
                "@namespaces": {
                    "floman": {
                        "name": "/floridaman/link-relations#"
                    }
                },
                "@controls": {
                    "collection": {
                        "href": "/api/articles/"
                    }
                },
                "items": [
                    {
                        "date": "02.01.2019"
                        "link": "https://www.wcjb.com/content/news/Florida-man-doesnt-get-straw-attacks-McDonalds-employee-503812581.html",
                        "headline": "Florida man doesn't get straw, attacks McDonald's employee",
                        "modtime": "Some modificationg date"
                    }
                ]
            }

# Group Users

All of these resources use the [User Profile](reference/profiles/user-profile). In error scenarios [Error Profile](reference/profiles/error-profile) is used.

## User Collection [/api/users/]

A list of all users known to the API. You can also add new user with POST, edit existing user using PUT and delete existing user using DELETE.

### Get Users [GET]

Gets all users from collection.

+ Relation: users-all
+ Request

    + Headers
    
            Accept: application/vnd.mason+json

+ Response 200 (application/vnd.mason+json)
    
    + Body

            {
                "@namespaces": {
                    "floman": {
                        "name": "/floridaman/link-relations#"
                    }
                },
                "@controls": {
                    "floman:user-by-name": {
                        "href": "/api/users/?{username}"
                    }
                },
                "items": [
                    {
                        "date": "02.01.2019"
                        "link": "https://www.wcjb.com/content/news/Florida-man-doesnt-get-straw-attacks-McDonalds-employee-503812581.html",
                        "headline": "Florida man doesn't get straw, attacks McDonald's employee",
                        "modtime": "Some modificationg date"
                    }
                ]
            }