# @import auth.http
# @ref login


### get books
GET /books
Authorization: Bearer {{login.access_token}}

### create book
POST /books
Authorization: Bearer {{login.token}}
Content-Type: application/json

{
    "title": "test book",
    "year": 2024,
    "authorId": 1
}
