name: Setup environment
description: Setup the environment used for testing and building flutter apps
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - run: pip install --upgrade pip
      shell: bash
    - run: pip install -r api/requirements.txt
      shell: bash
