# @import auth.http

###
GET /polls

###
# @name poll
# @ref profile
# @ref login
POST /polls
Content-Type: application/json
Authorization: Bearer {{ login.access_token }}

{
    "title": "TESTIIIIII",
    "description": "testing",
    "expires": "2024-03-29T17:53:57.494Z",
    "multipleAnswers": false,
    "private": false
}

###
GET /polls/{{poll.id}}
Content-Type: application/json

###
# @ref poll

GET /polls/{{poll.id}}/pollitems
Content-Type: application/json

###
DELETE /polls/{{poll.id}}
Content-Type: application/json
Authorization: Bearer {{login.access_token}}


###
# @ref poll
# @ref login
PATCH /polls/{{poll.id}}
Content-Type: application/json
Authorization: Bearer {{login.access_token}}

{
    "title": "new title",
    "private": true
}
