name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
         python-version: 3.8 
      - name: Install dependencies
        run: ./install.sh
      - name: Test & check syntax
        run: ./test.sh
      
